[build]
  # Build command to build the Next.js app and export the static site.
  command = "next build && next export"

  # Directory where the static site will be published.
  publish = "out"

[[plugins]]
  # Netlify plugin for Next.js integration.
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Environment variable to skip the Next.js plugin's automatic handling.
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
